import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { LEARN_PAGES } from "@/lib/learn/registry";
import { OFFER_PAGES } from "@/lib/offerPages";
import { LEARN_INDEX } from "@/lib/learnIndex";

// WHY THIS FILE EXISTS.
//
// Nothing tested the share cards until 2026-08-12, and it showed. The shared
// footer template said "Revenue Growth Coach" for months after that offer was
// retired, so every card the script had ever produced carried it, including
// five generated hours after the pivot for pages selling an AI automation
// partnership. The homepage card, the most-shared image on the site, still led
// with "Grow Your Revenue Without Growing Your Headcount".
//
// None of that was catchable by the checks that did exist. Those confirmed the
// files were on disk and the URLs resolved, which was true the whole time. The
// copy is only visible by opening the PNG, and nothing opens the PNG.
//
// So this reads the generator source, which is the only place the words live in
// text form, and holds it to the same copy law the pages obey. It cannot see
// the rendered artwork. It CAN see a retired phrase re-entering the source, and
// it can see a page pointing at a card the script does not know how to build.
//
// A card whose copy changes still has to be regenerated by hand and the PNG
// read back with human eyes. This test does not replace that. It replaces the
// possibility of a retired phrase sitting in the template unnoticed.

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../..");
const SRC = readFileSync(join(ROOT, "scripts/generate-og.mjs"), "utf8");
const FOOTER_JSX = readFileSync(join(ROOT, "components/Footer.jsx"), "utf8");

// Every single-quoted literal assigned to a copy-carrying field, plus the
// contents of the `chips` arrays. Style values are keyed on `style`, so they do
// not come through here.
function cardCopy() {
  const start = SRC.indexOf("const CARDS = {");
  expect(start, "CARDS object literal not found in generate-og.mjs").toBeGreaterThan(-1);
  const body = SRC.slice(start);

  const out = [];
  for (const m of body.matchAll(
    /(?:headline|subline|kicker|footnote|title|label):\s*'([^']*)'/g
  )) {
    out.push(m[1]);
  }
  for (const m of body.matchAll(/chips:\s*\[([^\]]*)\]/g)) {
    for (const c of m[1].matchAll(/'([^']*)'/g)) out.push(c[1]);
  }
  return out;
}

// Also sweep the shared templates above CARDS, because that is exactly where
// the retired line hid: not in any card, in the frame every card sits in.
function templateCopy() {
  const end = SRC.indexOf("const CARDS = {");
  const head = SRC.slice(0, end);
  return [...head.matchAll(/,\s*'([A-Za-z][^']{6,})'\s*[,)]/g)].map((m) => m[1]);
}

// Retired vocabulary. Each entry is [pattern, why], so a failure explains
// itself to whoever trips it rather than just naming a regex.
const BANNED = [
  [/\bcoach(es|ing)?\b/i, 'the coaching offer is retired; the company sells named builds'],
  [/\b15 years\b/i, 'the positioning number is "over a decade"; nothing new asserts fifteen'],
  [/\bfifteen years\b/i, 'the positioning number is "over a decade"'],
  [/\$\s?3M\b/i, 'the "$3M to $50M" band moved into ICP qualification, off public surfaces'],
  [/\$\s?50M\b/i, 'the "$3M to $50M" band moved into ICP qualification, off public surfaces'],
  [/revenue growth coach/i, 'the retired role line that shipped on every card for months'],
  // Retired PRODUCT names. Everything above is vocabulary and role lines, so a
  // card headed "Get Your Revenue Leak Scan" passed every assertion here while
  // naming an offer that no longer exists. A card is the worst place for that
  // to sit: the words live in a PNG nobody opens, and the page it is shared
  // from says the current name, so the two never contradict each other where
  // anyone can see it.
  //
  // The free diagnostic has been renamed more than once. All three earlier
  // names are dead; "AI Revenue Scan" is the only one allowed on a card.
  // "GTM Maturity Framework" is the LIVE framework name (renamed 2026-08-12
  // from "Revenue Operations Maturity Model") and is deliberately not banned.
  [/revenue growth scorecard/i, 'the diagnostic is the AI Revenue Scan; this name is retired'],
  [/revenue maturity score/i, 'the diagnostic is the AI Revenue Scan; this name is retired'],
  [/revenue leak scan/i, 'the diagnostic is the AI Revenue Scan; this name is retired'],
];

// Website copy spells contractions out: "do not", "you are", "it will". The
// `'s` form is deliberately not listed, because "Bradley's record" and "it's"
// are the same two characters and only the sentence tells them apart. Every
// other suffix is unambiguous.
const CONTRACTION = /\b\w+['’](?:t|re|ve|ll|d|m)\b/;

describe("open graph card copy", () => {
  const copy = cardCopy();
  const template = templateCopy();
  const all = [...copy, ...template];

  it("finds card copy to check at all", () => {
    // A refactor that renames the copy fields would otherwise make every
    // assertion below pass against an empty list.
    expect(copy.length).toBeGreaterThan(40);
    expect(all.join(" ")).toContain("The AI automation partner for B2B go-to-market");
  });

  it("carries no retired vocabulary", () => {
    for (const line of all) {
      for (const [pattern, why] of BANNED) {
        expect(pattern.test(line), `"${line}" is banned: ${why}`).toBe(false);
      }
    }
  });

  it("uses no em dashes and no contractions", () => {
    for (const line of all) {
      expect(line, `"${line}" contains an em dash`).not.toMatch(/—/);
      expect(CONTRACTION.test(line), `"${line}" contains a contraction`).toBe(false);
    }
  });

  it("recognises a contraction and a possessive apart", () => {
    // Guards the regex above, which is the one assertion here whose correctness
    // is not obvious by reading it.
    for (const bad of ["you're late", "do not, don't", "it'll work", "we've shipped", "I'm here"]) {
      expect(CONTRACTION.test(bad), `${bad} should read as a contraction`).toBe(true);
    }
    for (const ok of ["Bradley's record", "a client's stack", "six months"]) {
      expect(CONTRACTION.test(ok), `${ok} should not read as a contraction`).toBe(false);
    }
  });

  it("keeps the shared footer line identical to the site footer", () => {
    // The drift that produced the bug: the card template and the page footer
    // are two copies of one positioning line, and only one of them was updated
    // when the offer changed.
    const line = "The AI automation partner for B2B go-to-market";
    expect(SRC).toContain(`'${line}'`);
    expect(FOOTER_JSX).toContain(line);
  });

  it("ships with every card flagged unchanged", () => {
    // `changed: true` is the switch that tells the script to re-render a card.
    // Leaving one on means the next unrelated run rewrites a PNG nobody meant
    // to touch, which is how a share image changes without a commit that says
    // so. The committed state is always all-false.
    expect(SRC).not.toMatch(/changed:\s*true/);
  });

  it("can regenerate every card a page points at", () => {
    // Three cards were generated before the CARDS table existed and never got
    // an entry, so `--all` silently skips them and this test would fail without
    // saying anything useful. They are listed here rather than hidden: their
    // copy is clean, but they sit on an older template and cannot be
    // regenerated. Adding entries means re-rendering them onto the current
    // template, which is a visual change and an owner's call, not a sweep's.
    const PRE_TABLE_CARDS = [
      "og-learn-stage-1-reactive.png",
      "og-learn-crm-architecture.png",
      "og-learn-pipeline-stage-design.png",
    ];

    const referenced = new Set(
      [
        ...Object.values(LEARN_PAGES).map((p) => p.ogImage),
        ...Object.values(OFFER_PAGES).map((p) => p.ogImage),
        LEARN_INDEX.ogImage,
      ].map((url) => url.split("/").pop())
    );

    const generated = new Set(
      [...SRC.matchAll(/^ {2}'?([a-z0-9-]+)'?: \{$/gm)].map((m) => `og-${m[1]}.png`)
    );

    const orphans = [...referenced].filter(
      (f) => !generated.has(f) && !PRE_TABLE_CARDS.includes(f)
    );
    expect(orphans, "pages point at cards generate-og.mjs cannot build").toEqual([]);
  });
});
